### ISSUE TITLE
Item sorter tweak

### ISSUE THREAD

**Issue by valda** [valda/garybash#12]
This tweak should change to independent option. > 4fadd0bfb0cf32a8a2e9f4326637b84f096a9c39

**Comment by valda** [comment]
> mosanger:
> thanks for merging it into the source.
> an option would be really nice though. in case someone wants ammo first ;D
> how about differing between stimpacks and all the other aid too?

My god!
Sorry for the comment has been deleted by my mistake.

I think that it's convenient to put stimpacks above all other aid :)

**Comment by mosanger** [comment]
yes, that would be quite useful...
then chems and then food?

**Comment by valda** [comment]
done!
