### ISSUE TITLE
NoMerge yet imported ?

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#13]
<i>The following mods are tagged 'NoMerge'. These should be deactivated before
building the patch, and then imported into the patch during build.
*PostalProjectile.esp
- OADLCfix.esp</i>

I believe I tagged these myself because I wanted to keep from merging or importing content I had altered in my own patch made in FO3Edit. But the wording of this warning is such that it seems I should "imported into the patch during build." That seems quite odd and missleading in the case of the tag {{BASH:NoMerge}} and may apply to a case of a tag of {{BASH:Deactivate}}.
:::::QUOTE Readme::::::
New warnings about NoMerge/Deactivate tagged mods being active at rebuild time (they shouldn't be). 
::::End Quote:::::

UPDATE:OK I readdressed this to the Wrye Bash Development sight as it is still an issue in Directory revision: 398 of basher.py and not specific to Gary Bash.

**Comment by valda** [comment]
Thank you for the verification.
Can I close this issue once?

**Comment by Sativarg** [comment]
Yes Thank you.
