### ISSUE TITLE
Bash patch oblivion specific

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#14]
<b>found in Bosh.py</b>
GmstTweak(_('UOP Vampire Aging and Face Fix.esp'),
            _("Duplicate of UOP component that disables vampire aging (fixes a bug). Use instead of 'UOP Vampire Aging & Face Fix.esp' to save an esp slot."),
            'iVampirismAgeOffset',

<b>and almost all Actors tweeks</b>
<b>found in Bosh.py</b>
lass TweakActors(MultiTweaker):
    """Sets Creature stuff or NPC Skeletons, Animations or other settings to better work with mods or avoid bugs."""
    name = _('Tweak Actors')
    text = _("Tweak NPC and Creatures records in specified ways.")
    tweaks = sorted([
        MAONPCSkeletonPatcher(),
        VanillaNPCSkeletonPatcher(),
        RedguardNPCPatcher(),
        NoBloodCreaturesPatcher(),
        AsIntendedImpsPatcher(),
        AsIntendedBoarsPatcher(),
        #RWALKNPCAnimationPatcher(),
        #SWALKNPCAnimationPatcher(),
        ],key=lambda a: a.label.lower())

I'll keep looking unless you had already found these and I am just bugging you...
<b>found in Bosh.py</b>
class NamesTweak_Dwarven(MultiTweakItem):
    #--Config Phase -----------------------------------------------------------
    def **init**(self):
        self.activeTypes = ['ALCH', 'AMMO', 'APPA', 'ARMO', 'BOOK', 'BSGN', 'CLAS', 'CLOT', 'CONT', 'CREA', 'DOOR',
            'EYES', 'FACT', 'FLOR', 'HAIR','INGR', 'KEYM', 'LIGH', 'MISC', 'NPC_', 'RACE', 'SGST',
            'SLGM', 'SPEL','WEAP']
        MultiTweakItem.**init**(self,_("Lore Friendly Names: Dwarven -> Dwemer"),
            _('Rename any thing that is named X Dwarven or Dwarven X to Dwemer X/X Dwemer to follow lore better.'),
            'Dwemer',
            (('Lore Friendly Names: Dwarven -> Dwemer'),  'Dwemer'),
            )

**Comment by valda** [comment]
Thanks for reporting.
HEAD is very unstable now.
I recommend to use the previous version for a while :)

**Comment by valda** [comment]
It was fixed by mosanger!
Thanks.

**Comment by Sativarg** [comment]
Great. I was looking in the wrong page for all Commits. I was only seeing yours. Now I am looking in the proper page for the latest updates.
