### ISSUE TITLE
SoundPatcher throws an error (MreWthr has no attribute 'sound')

### ISSUE THREAD

**Issue by mosanger** [valda/garybash#15]
While trying to patch sounds into the batched patch, i encountered the error described above.
I tried to resolve the issue myself but now it doesn't seem to import and patch the whole struct.

While exploring the code i also fixed one small error regarding the sound-attributes of MreLigh and MreActi. (It's in my forked repository, at least i hope so)

(televator from fallout3nexus here, btw)

**Comment by valda** [comment]
Merged your commit.
I also confirm the issue of MreWthr.sounds structs. 
Fix of MreLigh and MreActi in SoundPatcher is all right.
Thank you very much!
