### ISSUE TITLE
NamesTweak + Inventory Sorter fails with weapons 

### ISSUE THREAD

**Issue by mosanger** [valda/garybash#19]
Everything else works perfectly.
However, all weapons will result in names like `(E29) \x07\x07Laser Pistol` instead of `\x07\x07(E29) Laser Pistol`

**Comment by valda** [comment]
Oh, thanks.
The cause is probably an execution order of the patch.

**Comment by mosanger** [comment]
yeah, i thought so too, but NamesPatcher_InventorySorter does come last in the order... :?

**Comment by valda** [comment]
Yes, but the list is sorted by the label.
fixed at d3157e9ae72e65150daa7c0aed7ff1740c4b5475

**Comment by mosanger** [comment]
Thanks :)
