### ISSUE TITLE
Astnetic: green ICON

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#2]
I made new Icons for Garybash with Irfanview by opening
C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\images

bash_16.png
bash_32.ico
bash_32.png
bash_32_2.png

and using Image>swap colors>RGB->GRB
I have my versions in a temporary folder in
 C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\images 
When I update to the new source codes I have been replacing the originals with my green ones. Here is a link to them if you want them:http://www.4shared.com/file/XJmxewxD/Gbash-Icons.html
here is a Screenshot:
http://img109.imageshack.us/img109/2981/newicons.jpg

**Comment by valda** [comment]
Thank you :)
New icons are merged.

**Comment by Sativarg** [comment]
YA thanks
