### ISSUE TITLE
FO3MasterUpdate.exe

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#20]
[@Valda](http://github.com/valda) I have been using the MasterUpdate functionality of FO3Edit for months now. I really helps stabilize my game. I remembered how Wrye Bash used to handle the implementation of App Buttons for Tes4View and found some of the old code commented in GaryBash so I modified this code, made 4 new Icons and added a batch file to C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\Extras and now I have BashStatusBar.buttons FO3MasterRestore and FO3MasterUpdate.
# I modified:
- Mopy\bash_default.ini
- Mopy\basher.py
- Mopy\bosh.py
# I added
- Mopy\Extras\masterupdate seup.bat
- Mopy\images\FO3MasterRestore16.png
- Mopy\images\FO3MasterRestore32.png
- Mopy\images\FO3MasterUpdate16.png
- Mopy\images\FO3MasterUpdate32.png

![Files changed](http://img36.imageshack.us/img36/6765/fileschanged.jpg)
![output](http://img25.imageshack.us/img25/8545/resultsnv.jpg)

[here are the changes](http://www.4shared.com/file/XIX6Jz1t/valda-garybash-Sativargs_edit.html) at 4shared if you would like to use them.

I want to implement the same function to disable ghosting before launching FO3MasterUpdate and Restore but that leads to load order troubles when FO3MasterUpdate does its thing so maybe you have some ideas.

**Comment by valda** [comment]
Thank you for contribution!
I'd like to introduce it.

**Comment by Sativarg** [comment]
Its yours feel free to improve it as Ghoasting results in load order disruption when FO3edit does the file organizing I had hoped to auto unghost as with BOSS. And command line swithes do exist for the alter-Egos of FO3Edit but I got lost on the implementation of them.

**Comment by Sativarg** [comment]
This has been incorporated so closing
