### ISSUE TITLE
new BOSS needs Flash launch code

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#21]
I have been testing the new BOSS soon to be released. when started from Flash it hangs badly. I traced the hang to the way Flash starts BOSS
from: basher.py
00011020 #------------------------------------------------------------------------------
00011021 class App_BOSS(App_Button):
00011022     """loads BOSS"""
00011023 
00011024     def Execute(self,event,extraArgs=None):
00011025         exeFose = bosh.dirs['app'].join('fose_loader.exe')
00011026         exeArgs = self.exeArgs
00011027         if self.foseArg != None and settings.get('bash.fose.on',False) and exeFose.exists():
00011028             exePath = exeFose
00011029             if self.foseArg != '': exeArgs += (self.foseArg,)
00011030         else:
00011031             exePath = self.exePath
00011032         exeArgs = (exePath.stail,)+exeArgs
00011033         if extraArgs: exeArgs += extraArgs
00011034         statusBar.SetStatusText(' '.join(exeArgs),1)
00011035         cwd = bolt.Path.getcwd()
00011036         exePath.head.setcwd()
00011037         progress = balt.Progress(_("Executing BOSS"))
00011038         if settings.get('bash.mods.autoGhost'):
00011039             progress(0.05,_("Processing... deghosting mods"))
00011040             ghosted = []
00011041             for root, dirs, files in os.walk(bosh.dirs['mods'].s):
00011042                 for name in files:
00011043                     fileLower = name.lower()
00011044                     if fileLower[-10:] == '.esp.ghost' or fileLower[-10:] == '.esm.ghost':
00011045                         if not name[:-6] in files:
00011046                             file = bosh.dirs['mods'].join(name)
00011047                             ghosted.append(fileLower)
00011048                             newName = bosh.dirs['mods'].join(name[:-6])
00011049                             file.moveTo(newName)
00011050         progress(0.55,_("Processing... launching BOSS."))
00011051         os.spawnv(os.P_WAIT,exePath.s,exeArgs) #<<here s.P_WAIT can be os.P_NOWAIT
00011052         if progress: progress.Destroy()
00011053         cwd.setcwd()
00011054 
00011055 #------------------------------------------------------------------------------

in the neww version there will be no need to "Processing... deghosting mods" and thus no need to P_WAIT. I am not sure why the BOSS process hangs in the new version when launched with Python as a parrent but I do know that tha following modified code works much better with the new and yet to be released BOSS

00011020 #------------------------------------------------------------------------------
00011021 class App_BOSS(App_Button):
00011022     """loads BOSS"""
00011023 
00011024     def Execute(self,event,extraArgs=None):
00011025         exeFose = bosh.dirs['app'].join('fose_loader.exe')
00011026         exeArgs = self.exeArgs
00011027         if self.foseArg != None and settings.get('bash.fose.on',False) and exeFose.exists():
00011028             exePath = exeFose
00011029             if self.foseArg != '': exeArgs += (self.foseArg,)
00011030         else:
00011031             exePath = self.exePath
00011032         exeArgs = (exePath.stail,)+exeArgs
00011033         if extraArgs: exeArgs += extraArgs
00011034         statusBar.SetStatusText(' '.join(exeArgs),1)
00011035         cwd = bolt.Path.getcwd()
00011036         exePath.head.setcwd()
00011037         progress = balt.Progress(_("Executing BOSS"))
00011038 #        if settings.get('bash.mods.autoGhost'):
00011039 #            progress(0.05,_("Processing... deghosting mods"))
00011040 #           ghosted = []
00011041 #           for root, dirs, files in os.walk(bosh.dirs['mods'].s):
00011042 #               for name in files:
00011043 #                   fileLower = name.lower()
00011044 #                   if fileLower[-10:] == '.esp.ghost' or fileLower[-10:] == '.esm.ghost':
00011045 #                       if not name[:-6] in files:
00011046 #                           file = bosh.dirs['mods'].join(name)
00011047 #                           ghosted.append(fileLower)
00011048 #                           newName = bosh.dirs['mods'].join(name[:-6])
00011049 #                           file.moveTo(newName)
00011050         progress(0.55,_("Processing... launching BOSS."))
00011051         os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)
00011052         if progress: progress.Destroy()
00011053         cwd.setcwd()
00011054 
00011055 #------------------------------------------------------------------------------

**Comment by Sativarg** [comment]
I have relayed the suggestions made here to the BOSS team
NOTE:the code below is from basher.py
http://code.google.com/p/better-oblivion-sorting-software/issues/detail?id=59
+++++++++++++++content+++++++++++++
 Reported by sativarg, Today (moments ago)

What steps will reproduce the problem?
1.launch BOSS with Wrye Flash
2.
3.

What is the expected output?:near instant output to browser What do you see instead?:long lag before output

What version of the product are you using? On what operating system?
r1557

Please provide any additional information below.
I have suggested the following be made ready before new BOSS is released
http://github.com/valda/garybash/issues/issue/21
===============================content=====
I have been testing the new BOSS soon to be released. when started from Flash it hangs badly. I traced the hang to the way Flash starts BOSS
00011020 #------------------------------------------------------------
00011021 class App_BOSS(App_Button):
00011022     """loads BOSS"""
00011023 
00011024     def Execute(self,event,extraArgs=None):
00011025         exeFose = bosh.dirs['app'].join('fose_loader.exe')
00011026         exeArgs = self.exeArgs
00011027         if self.foseArg != None and settings.get('bash.fose.on',False) and exeFose.exists():
00011028             exePath = exeFose
00011029             if self.foseArg != '': exeArgs += (self.foseArg,)
00011030         else:
00011031             exePath = self.exePath
00011032         exeArgs = (exePath.stail,)+exeArgs
00011033         if extraArgs: exeArgs += extraArgs
00011034         statusBar.SetStatusText(' '.join(exeArgs),1)
00011035         cwd = bolt.Path.getcwd()
00011036         exePath.head.setcwd()
00011037         progress = balt.Progress(_("Executing BOSS"))
00011038         if settings.get('bash.mods.autoGhost'):
00011039             progress(0.05,_("Processing... deghosting mods"))
00011040             ghosted = []
00011041             for root, dirs, files in os.walk(bosh.dirs['mods'].s):
00011042                 for name in files:
00011043                     fileLower = name.lower()
00011044                     if fileLower[-10:] == '.esp.ghost' or fileLower[-10:] == '.esm.ghost':
00011045                         if not name[:-6] in files:
00011046                             file = bosh.dirs['mods'].join(name)
00011047                             ghosted.append(fileLower)
00011048                             newName = bosh.dirs['mods'].join(name[:-6])
00011049                             file.moveTo(newName)
00011050         progress(0.55,_("Processing... launching BOSS."))
00011051         os.spawnv(os.P_WAIT,exePath.s,exeArgs) #<<here s.P_WAIT can be os.P_NOWAIT
00011052         if progress: progress.Destroy()
00011053         cwd.setcwd()
00011054 
00011055 #--------------------------------------------------------

in the neww version there will be no need to "Processing... deghosting mods" and thus no need to P_WAIT. I am not sure why the BOSS process hangs in the new version when launched with Python as a parrent but I do know that tha following modified code works much better with the new and yet to be released BOSS

00011020 #----------------------------------------------------
00011021 class App_BOSS(App_Button):
00011022     """loads BOSS"""
00011023 
00011024     def Execute(self,event,extraArgs=None):
00011025         exeFose = bosh.dirs['app'].join('fose_loader.exe')
00011026         exeArgs = self.exeArgs
00011027         if self.foseArg != None and settings.get('bash.fose.on',False) and exeFose.exists():
00011028             exePath = exeFose
00011029             if self.foseArg != '': exeArgs += (self.foseArg,)
00011030         else:
00011031             exePath = self.exePath
00011032         exeArgs = (exePath.stail,)+exeArgs
00011033         if extraArgs: exeArgs += extraArgs
00011034         statusBar.SetStatusText(' '.join(exeArgs),1)
00011035         cwd = bolt.Path.getcwd()
00011036         exePath.head.setcwd()
00011037         progress = balt.Progress(_("Executing BOSS"))
00011038 #        if settings.get('bash.mods.autoGhost'):
00011039 #            progress(0.05,_("Processing... deghosting mods"))
00011040 #           ghosted = []
00011041 #           for root, dirs, files in os.walk(bosh.dirs['mods'].s):
00011042 #               for name in files:
00011043 #                   fileLower = name.lower()
00011044 #                   if fileLower[-10:] == '.esp.ghost' or fileLower[-10:] == '.esm.ghost':
00011045 #                       if not name[:-6] in files:
00011046 #                           file = bosh.dirs['mods'].join(name)
00011047 #                           ghosted.append(fileLower)
00011048 #                           newName = bosh.dirs['mods'].join(name[:-6])
00011049 #                           file.moveTo(newName)
00011050         progress(0.55,_("Processing... launching BOSS."))
00011051         os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)
00011052         if progress: progress.Destroy()
00011053         cwd.setcwd()
00011054 
00011055 #----------------------------------------------------------
============================end-content=====

Obviously WrinklyNinja1 was correct and the problem was in the way Flash was launching the new BOSS-f.exe I also changed the code that sets the target so it will launch Boss-f.exe and not Boss-f.bat. launching from the batch file does not effect the run time much but it is unnecessary. here is an altered copy of basher.py.

+++++++++++++end Content++++++++++

**Comment by Sativarg** [comment]
here is a link to my version of Basher.py
http://www.4shared.com/file/VC37kk5C/basher-sept-25-2010.html
here is a compiled version of the new boss for testing gos in the data folder and you need to copy the master list out of the BOSS folder till I figure out how to get Flash to look in the correct place for it.
removed link and 4shared boss content

Also Now that BOSS is exactly the same weather it is running in Oblivion Morrowind or Fallouts data folder I think we can drop the -f from Boss-f.exe in Basher.py and every where else. I'll update my presentations accordingly now.

**Comment by Sativarg** [comment]
OK I have edited Basher to look in data/boss/ for the masterlist now
00007780         self.path = bosh.dirs['mods'].join('/boss/masterlist.txt')

++++++++++++Basher.py+++++++++
00007773 #------------------------------------------------------------------------------
00007774 class Mods_BossMasterList(Link):
00007775     """Open Data/masterlist.txt."""
00007776     def AppendToMenu(self,menu,window,data):
00007777         Link.AppendToMenu(self,menu,window,data)
00007778         menuItem = wx.MenuItem(menu,self.id,_('masterlist.txt...'))
00007779         menu.AppendItem(menuItem)
00007780         self.path = bosh.dirs['mods'].join('/boss/masterlist.txt')
00007781         menuItem.Enable(self.path.exists())
00007782 
00007783     def Execute(self,event):
00007784         """Handle selection."""
00007785         self.path.start()
00007786 
00007787 #------------------------------------------------------------------------------
++++++++++++Basher.py+++++++++
Updated basher link
http://www.4shared.com/file/3V4iCBCX/basher_sept_26_now_looks_for_M.html

**Comment by Sativarg** [comment]
Now I have found where the component bosh.py finds the tag-suggestions and amended the path to include the new boss folder

00010570         self.bossMasterPath = dirs['mods'].join('/boss/masterlist.txt')

+++++++++bosh.py+++++++
00010564 class ConfigHelpers:
00010565     """Encapsulates info from mod configuration helper files (BOSS masterlist, etc.)"""
00010566 
00010567     def **init**(self):
00010568         """Initialialize."""
00010569         #--Boss Master List or if that doesn't exist use the taglist
00010570         self.bossMasterPath = dirs['mods'].join('/boss/masterlist.txt')
00010571         if not self.bossMasterPath.exists():
00010572             self.bossMasterPath = dirs['patches'].join('taglist.txt')
00010573         self.bossMasterTime = 0
00010574         self.bossMasterTags = {}
00010575         #--Mod Rules
00010576         self.name_ruleSet = {}
+++++++++bosh.py+++++++
new bosh.py link

http://www.4shared.com/file/f2MMH2JI/bosh-sept26_now_looks_in_boss_.html

**Comment by Sativarg** [comment]
Well i messed up again as pacificmorrowind already has this taken care of so this thread is redundant for the most part. I am very sorry to be such a bother.

Comment 6  by project member pacificmorrowind, Today (98 minutes ago)

As I did mention (admittedly on the Bethsoft thread which I'd guess you probably don't hang out very much on), I've done teh necessary code changes in Wrye Bash to deal happily and as efficiently as possible with either old or new versions of BOSS. Also to handle forwarding of the args (-u, -V-, -r 1, -r 2) if the user presses the U key, the V key or the R key or the Shift R key (or a combination thereof). Also works with the Userlist (all permutations of possible changes). So I'll be just diffing that and then applying it as a patch onto my fork of Wrye Flash, which I'm sure Valda will pull pretty soon after he's next online.
Pacific Morrowind

**Comment by valda** [comment]
Thanks for reporting :) 
Fixed at afe10ab9c6ad89add26bb4262758e91a63b565b7

**Comment by valda** [comment]
close
