### ISSUE TITLE
Still major delay on BOSS load

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#27]
I have repeatadly commented on this. When running boss from Flash or Bash or Mash there is a major lag.
_**but if I edit one thing in basher.py *_*

00011108                 os.spawnv(os.P_WAIT,exePath.s,exeArgs)

**change to**

00011108                 os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)
**_this is fixed**_

00011106             progress(0.05,_("Processing... launching BOSS."))
00011107             try:
00011108                 os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)
00011109             except Exception, error:
00011110                 print str(error)
00011111                 print _("Used Path: %s") % exePath.s
00011112                 print _("Used Arguments: "), exeArgs
00011113                 print
00011114                 raise
00011115             finally:
00011116                 if progress: progress.Destroy()
00011117                 if lockTimesActive: 
00011118                     settings['bosh.modInfos.resetMTimes'] = bosh.modInfos.lockTimes = lockTimesActive
00011119                 cwd.setcwd()
00011120         else:
00011121             raise StateError('Application missing: %s' % self.exePath.s)

**Comment by valda** [comment]
Thanks for your contribution.
But, In the situation of ghosting, that doesn't seem to work.

**Comment by Sativarg** [comment]
I am using the new BOSS found here
BOSS 1-61 Beta
[http://www.tesnexus.com/downloads/file.php?id=20516 Better Oblivion Sorting Software - BOSS]
257kb
1,414 downloads
919 downloads (unique)
20:21, 19 October 2010
Latest version. Hopefully no bugs, but still beta.
This version handles Ghosted files on its own.

Better Oblivion Sorting Software Log
© Random007 & the BOSS development team, 2009-2010. Some rights reserved.
CC Attribution-Noncommercial-No Derivative Works 3.0
v1.6 (23 Spetember 2010)
Special Mod Detection
Recognised And Re-ordered Mod Files
FalloutNV.esm
    \* Note: Masterlist Information: $Revision: 1710 $, $Date: 2010-10-21 02:24:31 -0400 (Thu, 21 Oct 2010) $, $LastChangedBy: mosanger $
ClassicPack.esm
MercenaryPack.esm
TribalPack.esm
CaravanPack.esm
Clean Up New Vegas.esp
VMS44Fixed.esp
Davisonnoattack.esp
Lucky 38 Suite Respawn Fix.esp - Ghosted
Vault11HouseFix.esp - Ghosted
VeronicaFix.esp - Ghosted
Weathered10mmFixed.esp
ScribeCounterFix.esp
Karma Fix - NCRCF Powder Ganger.esp
NV Interiors - El Ray Motel.esp
NV Interiors - West Vegas Fringe.esp
01RedRockCanyonRanch.esp
PortableCampsite.esp
I Fought the Law Workaround.esp - Ghosted
BetterLuckySuite.esp
xatmosSkillPerks.esp
Night Vision Sunglasses.esp
QS_Blackwolf_NV_Backpackmod.esp
BetterRepairKits.esp - Ghosted
Solar's Bottled Water.esp
Automatic Service Rifle.esp - Ghosted
Better Binoculars Max.esp - Ghosted
Desert Armor.esp
KDS Wearable Backpacks.esp
Essentialcompanions.esp - Ghosted
CManagerie.esp
T3T_MiscItemIconsNV.esp - Ghosted
aaaJNFCamp.esp
My First Chemistry Set.esp
Wasteland Explorer.esp
AddEmptyBottle.esp - Ghosted
Imp's Timescale Adjuster.esp
Lighter books.esp - Ghosted
less_aggressive_cazadores.esp - Ghosted
nv_passive_critters_norm_gecko.esp - Ghosted
RasRepair.esp - Ghosted
Improved Throwing1.esp
FreeplayafterMQNVv1_6.esp - Ghosted
Improved ammo.esp
KDS Performance Ultimate.esp
DarNifiedUINV.esp
SoftDrinksRestoreDehydration.esp - Ghosted
Realistic Death & Dismemberment Physics.esp
URWLNV.esp
Bashed Patch, 0.esp
Unrecogised Mod Files
Reorder these by hand using your favourite mod ordering utility.
Unknown mod file: MISC - Preorder DLC - Caravan.esp
Unknown mod file: MISC - Preorder DLC - Classic.esp
Unknown mod file: MISC - Preorder DLC - Mercenary.esp
Unknown mod file: MISC - Preorder DLC - Tribal.esp
Unknown mod file: MISC - Base.esp
Unknown mod file: my patch1.esp
Done.
all the items Ghosted are still sorted
