### ISSUE TITLE
RE: lag when loading boss with any version of Wrye FL/B/M/[ash]/NV

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#29]
I hit the wrong button and closed this by mistake.
Is it possible to forgo the progress bar when using any "ash to load BOSS?
the command os.P_WAIT,exe seems to result in a unnecessary delay when loading BOSS.exe. As soon as I modify the line to "os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)" the delay is gone and in the case of the latest BOSS version unghosting is not needed. If the os.P_WAIT,exe is necessary for unlocking then please consider allowing the  P_NOWAIT be implemented if no file locking is set.

valda about 3 hours ago | link

Thanks for your contribution.
But, In the situation of ghosting, that doesn't seem to work.
Comment
Thanks for your contribution. But, In the situation of ghosting, that doesn't seem to work.
or cancel
Sativarg just now | link | edit | delete

I am using the new BOSS found here
BOSS 1-61 Beta
[http://www.tesnexus.com/downloads/file.php?id=20516 Better Oblivion Sorting Software - BOSS] 257kb
1,414 downloads
919 downloads (unique)
20:21, 19 October 2010
Latest version. Hopefully no bugs, but still beta.
This version handles Ghosted files on its own.

Better Oblivion Sorting Software Log
© Random007 & the BOSS development team, 2009-2010. Some rights reserved.
CC Attribution-Noncommercial-No Derivative Works 3.0
v1.6 (23 Spetember 2010)
Special Mod Detection
Recognised And Re-ordered Mod Files
FalloutNV.esm
- Note: Masterlist Information: $Revision: 1710 $, $Date: 2010-10-21 02:24:31 -0400 (Thu, 21 Oct 2010) $, $LastChangedBy: mosanger $

CaravanPack.esm
Clean Up New Vegas.esp
VMS44Fixed.esp
Davisonnoattack.esp
Lucky 38 Suite Respawn Fix.esp - Ghosted
Vault11HouseFix.esp - Ghosted
VeronicaFix.esp - Ghosted
Weathered10mmFixed.esp
ScribeCounterFix.esp
Karma Fix - NCRCF Powder Ganger.esp
NV Interiors - El Ray Motel.esp
NV Interiors - West Vegas Fringe.esp
01RedRockCanyonRanch.esp
PortableCampsite.esp
I Fought the Law Workaround.esp - Ghosted
BetterLuckySuite.esp
xatmosSkillPerks.esp
Night Vision Sunglasses.esp
.esp BetterRepairKits.esp - Ghosted
Solar's Bottled Water.esp
Automatic Service Rifle.esp - Ghosted
Better Binoculars Max.esp - Ghosted
Desert Armor.esp
KDS Wearable Backpacks.esp
Essentialcompanions.esp - Ghosted
CManagerie.esp
T3T_MiscItemIconsNV.esp - Ghosted
aaaJNFCamp.esp
My First Chemistry Set.esp
Wasteland Explorer.esp
AddEmptyBottle.esp - Ghosted
Imp's Timescale Adjuster.esp
Lighter books.esp - Ghosted
less_aggressive_cazadores.esp - Ghosted
nv_passive_critters_norm_gecko.esp - Ghosted
RasRepair.esp - Ghosted
Improved Throwing1.esp
FreeplayafterMQNVv1_6.esp - Ghosted
Improved ammo.esp
KDS Performance Ultimate.esp
DarNifiedUINV.esp
SoftDrinksRestoreDehydration.esp - Ghosted
Realistic Death & Dismemberment Physics.esp
URWLNV.esp
Bashed Patch, 0.esp
Unrecogised Mod Files
Reorder these by hand using your favourite mod ordering utility.
Unknown mod file: MISC - Preorder DLC - Caravan.esp
Unknown mod file: MISC - Preorder DLC - Classic.esp
Unknown mod file: MISC - Preorder DLC - Mercenary.esp
Unknown mod file: MISC - Preorder DLC - Tribal.esp
Unknown mod file: MISC - Base.esp
Unknown mod file: my patch1.esp
Done.
all the items Ghosted are still sorted

**Comment by valda** [comment]
I didn't know that BOSS supported Ghosting!
Thank you for telling me, again.

**Comment by Sativarg** [comment]
Yes you have to get the latest SVN or the one from the TesNexus site.
Building the SVN can be a bit hairy as it require a library called BOOST that uses like 5 gigs of HD. 

The Better Oblivion Sorting Software latest at 
BOSS 1-61 Beta
257kb
1,689 downloads
1,087 downloads (unique)
19:21, 19 October 2010
Latest version. Hopefully no bugs, but still beta.
 BOSS 1-61 Beta
257kb
1,689 downloads
1,087 downloads (unique)
19:21, 19 October 2010
Latest version. Hopefully no bugs, but still beta.
BOSS 1-61 Beta
257kb
1,689 downloads
1,087 downloads (unique)
19:21, 19 October 2010
Latest version. Hopefully no bugs, but still beta.
BOSS 1-61 Beta 19:21, 19 October 2010
http://www.tesnexus.com/downloads/file.php?id=20516
