### ISSUE TITLE
Mod File Command>Nvidea fog fix Error and CELL.XCLL

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#3]
To reproduce in GaryBash open Mods tab
right-click a mod with an interior cell
Choose Nvidea fog fix
###### #####Result:

Traceback (most recent call last):
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\basher.py", line 7852, in Execute
    cleanMod.clean(SubProgress(progress,index,index+1))
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\bosh.py", line 14988, in clean
    color,near,far,rotXY,rotZ,fade,clip = ins.unpack('=12s2f2l2f',size,'CELL.XCLL')
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\bosh.py", line 473, in unpack
    return struct.unpack(format,self.ins.read(size))
  File "C:\Python25\lib\struct.py", line 87, in unpack
    return o.unpack(s)
struct.error: unpack requires a string argument of length 36
****************_Close result**_********************
This error I believe is related to a differance in the CELL.XCLL formats of FO3 vs Oblivion.
Note: "Fog Power" element is found under CELL.XCLL in fallout and not in Oblivion
Jpeg example from TES4Edit and FO3Edit
http://img709.imageshack.us/img709/4935/xcellfo3vsob.jpg
REFF:
Nvidia Fog Fix - http://wryebash.netai.net/#NvidiaFogFix
Unpack Expects the Wrong Number of Bytes - http://www.pubbs.net/200907/python/62701-unpack-expects-the-wrong-number-of-bytes.html

**Comment by valda** [comment]
Thanks.
"NVidia fog fix" is unnecessary in Fallout 3.

SHA: 0a42b35507b6a6eb1014065df4e64964809ab975

**Comment by Sativarg** [comment]
I have found 1 cell in witch I experience the Blackout. I have uninstalled the mod now though so its no big deal. Why is it unnecessary in FO3?

**Comment by valda** [comment]
Really?
I didn't hear that the nVidia blankscreen bug occurred in Fallout 3.
If it is recovered by measures same as Oblivion, I'll fix "nVidia fog fix".

**Comment by valda** [comment]
maybe fixed.

SHA: fd4ff415245097c4e7a39d360ab5dad2844d4a1b

**Comment by Sativarg** [comment]
RE:If it is recovered by measures same as Oblivion
I cant be sure I went into the cell in the GECK but I wasn't able to find the right way to edit close fog or whatever. then I stopped using the mod for other reasons.

RE:maybe fixed.
great I'll test it later.
