### ISSUE TITLE
FONVmasterupdate setup

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#33]
The batch file I made is out of date for Fallout New Vegas 

Here is an updated batch file
[FONVmasterupdate setup.7z - 4shared.com](http://www.4shared.com/file/lfnQhFPR/FONVmasterupdate_setup.html)

was the file
Fallout New Vegas\Mopy\Extras\masterupdate setup.bat

**Comment by valda** [comment]
Updated it.
Thanks!

**Comment by Sativarg** [comment]
thank you...
