### ISSUE TITLE
how I speed up BOSS

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#34]
On my system when I run [Better Oblivion Sorting Software - BOSS @ TES Nexus](http://www.tesnexus.com/downloads/file.php?id=20516)
     BOSS 1-62 Beta
        301kb
        18:00, 1 November 2010
        Added support for Fallout: New Vegas, added a few new features, fixed a crash bug. Hopefully stable.

I get a major lag if I start it with any version of Wrye M / B / FL / ash / NV so I made this little Python patch to edit Basher .py every time I update it.

```
#------------------------------------------------------------------
#           Name: search_and_replace_basher_fix.py
#         Author: Kevin Harris edited by Sativarg
#  Last Modified: 11/06/2010
#    Description: Just helps my system deal with
#                 Wrye M / B / FL / ash / NV
#                          opening BOSS
#------------------------------------------------------------------

import os
import sys
import fileinput

textToSearchFor   = 'os.spawnv(os.P_WAIT,exePath.s,exeArgs)'
textToReplaceWith = 'os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)'
fileToSearch      = 'basher.py'


oldFileName  = 'old_' + fileToSearch
tempFileName = 'temp_' + fileToSearch

# If there's already an 'old_' prefixed backup file there from
# a previous run, remove it...
if os.path.isfile( oldFileName ):
    os.remove( oldFileName )

tempFile = open( tempFileName, 'w' )

for line in fileinput.input( fileToSearch ):
    tempFile.write( line.replace( textToSearchFor, textToReplaceWith ) )

tempFile.close()

# Rename the original file by prefixing it with 'old_'
os.rename( fileToSearch, oldFileName )

# Rename the temporary file to what the original was named...
os.rename( tempFileName, fileToSearch )
```

**Comment by valda** [comment]
I read a launch code of BOSS once again,
When applied the patch, postprocessing for locktimes is no longer performed to suitable timing.
And to be honest, I'd like to keep the BOSS launch code same as upstream(WryeBash), for maintenance :)
How about consulting with the upstream?

**Comment by Sativarg** [comment]
OK sorry
I have posted an issue at [SourceForge.net: Oblivion Works: Detail: 3090292 - major lag when "Executing BOSS"](- http://sourceforge.net/tracker/index.php?func=detail&aid=3090292&group_id=284958&atid=1207901) but no one seems to have a problem with boss taking 40 to 50 seconds to run. I have reinstalled windows because my hard drive was messing up and there was no change to the way BOSS acted. some day others may have the same problem I have been seeing.

I'll stop bugging you about it.

**Comment by Sativarg** [comment]
closing

**Comment by valda** [comment]
Hmm, it's strange that processing of BOSS takes 40-50 seconds.
If you enable "Always Update BOSS Masterlist prior to running BOSS.", how about turning this off?

**Comment by Sativarg** [comment]
This started back when the BOSS team was first testing new code to enable the user to place personal mods into the load order with the User Rules. I was beta testing it and noticed the lag

[Issue 36 - better-oblivion-sorting-software - Sorting user files - Project Hosting on Google Code](http://code.google.com/p/better-oblivion-sorting-software/issues/detail?id=36)

I have tried every variation of scenario even before the update feature existed and always the lag has persisted until I Said NO to WAIT in that one line of code.
os.spawnv(os.P_NOWAIT,exePath.s,exeArgs)

I have reinstalled Windows XP
I have booted clean using msconfig.exe
[How to configure Windows XP to start in a "clean boot" state](http://support.microsoft.com/kb/310353)

I analyzed BOSS.exe, cmd.exe /c start BOSS\BOSSlog.html, "D:\Python26\pythonw.exe" and "\Mopy\Wrye Bash Launcher.pyw" with [Process Monitor](http://technet.microsoft.com/en-us/sysinternals/bb896645.aspx)

http://img251.imageshack.us/img251/6293/analysedwait.jpg

As you can see in the image above the time  taken to run is mostly attributable to ...\cmd.exe /c start BOSS\BOSSlog.html

It makes no difference if I use Firefox or IE to display the log.

http://img191.imageshack.us/img191/984/withnowait.jpg 
^^^this is after placing NOWAIT^^^

the graph shows only activity from the start of BOSS to the opening of the log file with Internet Explorer. the difference is striking.
