### ISSUE TITLE
Creating bashed patch

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#4]
Using GaryBash 13
Rebuilding Bashed Patch, 0.esp
I reverted to the blank default file after first attempt failed.
Still have error as follows.
Window title:
**pythonw wxPython: stdout/stderr**
Traceback (most recent call last):
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\basher.py", line 4613, in Execute
    raise
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\basher.py", line 4572, in Execute
    patchFile.initData(SubProgress(progress,0,0.1))
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\bosh.py", line 15245, in initData
    patcher.initData(SubProgress(progress,index))
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\bosh.py", line 16042, in initData
    temp_id_data[fid] = dict((attr,record.**getattribute**(attr)) for attr in recAttrs)
  File "C:\Program Files\Bethesda Softworks\Fallout 3\Mopy\bosh.py", line 16042, in <genexpr>
    temp_id_data[fid] = dict((attr,record.**getattribute**(attr)) for attr in recAttrs)
AttributeError: 'MreLigh' object has no attribute 'largeIconPath'
**end window**

**_note**_
Commit b0ec3d176c3cdeedcb4496174e4a57ddd7d36c98 to valda's garybash - GitHub - http://github.com/valda/garybash/commit/b0ec3d176c3cdeedcb4496174e4a57ddd7d36c98
Fixed MreLigh.
valda (author)
February 06, 2010

**Troubleshooting:**
I began eliminating items to be imported 
When I eliminate "Import Graphics" for item "Destruction - Main.esp" I am able to complete Rebuilt Patch
http://img194.imageshack.us/img194/126/importgraphics.jpg

**Comment by Sativarg** [comment]
Update:
edited Bosh.py line 15989
**Python**
       #--Type Fields
        recAttrs_class = self.recAttrs_class = {}
        for recClass in (MreBsgn,MreLscr, MreClas, MreLtex, MreRegn):
            recAttrs_class[recClass] = ('iconPath',)
        for recClass in (MreActi, MreDoor, MreFlor, MreFurn, MreGras, MreStat, MreMstt):
            recAttrs_class[recClass] = ('model',)
        for recClass in (MreAlch, MreAmmo, MreAppa, MreBook, MreIngr, MreKeym, MreLigh, MreMisc, MreSgst, MreSlgm, MreTree):
            recAttrs_class[recClass] = ('model',)
        for recClass in (MreNote,):

*\* end code**

**older code**

```
   #--Type Fields
    recAttrs_class = self.recAttrs_class = {}
    for recClass in (MreBsgn,MreLscr, MreClas, MreLtex, MreRegn):
        recAttrs_class[recClass] = ('iconPath',)
    for recClass in (MreActi, MreDoor, MreFlor, MreFurn, MreGras, MreStat, MreMstt):
        recAttrs_class[recClass] = ('model',)
    for recClass in (MreAlch, MreAmmo, MreAppa, MreBook, MreIngr, MreKeym, MreLigh, MreMisc, MreSgst, MreSlgm, MreTree):
        recAttrs_class[recClass] = ('largeIconPath','smallIconPath','model')
    for recClass in (MreNote,):
        recAttrs_class[recClass] = ('largeIconPath','smallIconPath','model','texture')
    for recClass in (MreWeap,):
        recAttrs_class[recClass] = ('largeIconPath','smallIconPath','model','shellCasingModel','scopeModel','worldModel','firstPersonModel','animationType','gripAnimation','reloadAnimation')
    for recClass in (MreArmo, MreClot):
```

*\* end older code **

This allowed me to include the item 
results:

<h1><a name='ImportGraphics'>Import Graphics</a></h1>

<h3><a name='SourceMods'>Source Mods</a></h3>

<p class=list-1>&bull;&nbsp; xCALIBR.esm
<p class=list-1>&bull;&nbsp; Destruction - Main.esp
<p class=list-1>&bull;&nbsp; xCALIBR_FWE5_Override.esp
<p class=empty>&nbsp;</p>

<h3><a name='ModifiedRecords'>Modified Records</a></h3>

<p class=empty>&nbsp;</p>

<h1><a name='ImportInventory'>Import Inventory</a></h1>

<h3><a name='SourceMods'>Source Mods</a></h3>

**Comment by valda** [comment]
Fixed it!
Thanks

SHA: 839c6d1f58c2e904a1fec10c2efb7e588904ef29
