### ISSUE TITLE
Fallout3 1.0/1.1/1.4 Swapping ERROR

### ISSUE THREAD

**Issue by Sativarg** [valda/garybash#5]
I fixed by the following change to  BOSH.PY

 #--Fallout3 1.0/1.1/1.4 Swapping -----------------------------------------------
     def getFallout3Versions(self):
         """Returns tuple of Fallout3 versions."""
         reFallout3 = re.compile('^Fallout3(|_1.0|_1.1||_1.4~).esm$')
         self.voAvailable.clear()
         for name,info in self.data.iteritems():
             maFallout3 = reFallout3.match(name.s)
             if maFallout3 and info.size in self.size_voVersion:
                 self.voAvailable.add(self.size_voVersion[info.size])
         self.voCurrent = self.size_voVersion.get(self.data[GPath('Fallout3.esm')].size,None

Note the "~" symbol in line# 00009900
reFallout3 = re.compile('^Fallout3(|_1.0|_1.1||_1.4~).esm$') #fixed
reFallout3 = re.compile('^Fallout3(|_1.0|_1.1||_1.4).esm$') #old

Now matches:
 #--Fallout3 version 
         self.version_voSize = {
             '1.0':int(_("288769595")),
             '1.1':int(_("288771181")),
             '1.4~':int(_("288771262"))}
         self.size_voVersion = bolt.invertDict(self.version_voSize)
         self.voCurrent = None
         self.voAvailable = set(

**Comment by valda** [comment]
Thanks for reporting.
Unified the formats of the label of ModInfos.version_voSize.
(for consistency to original WryeBash)
- SHA: ce6eeef43a86f6cd2bf78346668a4580c2bb40e3

**Comment by Sativarg** [comment]
Better than my work around. I wondered why the "~" was there.
